# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so100_follower \
  --robot.left_arm_port=/dev/tty.usbmodem5A460851411 \
  --robot.right_arm_port=/dev/tty.usbmodem5A460812391 \
  --robot.id=bimanual_follower \
  --robot.cameras='{
    left: {"type": "opencv", "index_or_path": 0, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    right: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30}
  }' \
  --teleop.type=bi_so100_leader \
  --teleop.left_arm_port=/dev/tty.usbmodem5A460828611 \
  --teleop.right_arm_port=/dev/tty.usbmodem5A460826981 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so100-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
import numbers
import sys
import time
from collections.abc import Mapping
from dataclasses import asdict, dataclass, field, is_dataclass
from pathlib import Path
from pprint import pformat
from typing import Any

if __package__ is None or __package__ == "":
    repo_src = Path(__file__).resolve().parents[2]
    repo_src_str = str(repo_src)
    if repo_src_str not in sys.path:
        sys.path.insert(0, repo_src_str)

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_so100_follower,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_so100_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    so100_leader,
    so101_leader,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_devices
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


def _get_runtime_state_value(runtime_state: Any, key: str, default: Any = None) -> Any:
    if runtime_state is None:
        return default
    if isinstance(runtime_state, dict):
        return runtime_state.get(key, default)
    return getattr(runtime_state, key, default)


def _set_runtime_state_value(runtime_state: Any, key: str, value: Any) -> None:
    if runtime_state is None:
        return
    if isinstance(runtime_state, dict):
        runtime_state[key] = value
    else:
        setattr(runtime_state, key, value)


def _coerce_hook_result(result: Any) -> dict[str, Any] | None:
    if result is None:
        return None
    if isinstance(result, dict):
        return result
    if is_dataclass(result) and not isinstance(result, type):
        return asdict(result)
    if hasattr(result, "__dict__"):
        return {key: value for key, value in vars(result).items() if not key.startswith("_")}
    return {"value": result}


def _invoke_hook(hook: Any, method_name: str, **kwargs: Any) -> dict[str, Any] | None:
    if hook is None:
        return None

    hook_method = getattr(hook, method_name, None)
    if callable(hook_method):
        return _coerce_hook_result(hook_method(**kwargs))

    if callable(hook):
        return _coerce_hook_result(hook(**kwargs))

    raise TypeError(f"Hook {hook!r} does not provide `{method_name}(...)` and is not callable.")


def _log_step_event(step_event_logger: Any, event_name: str, **payload: Any) -> None:
    if step_event_logger is None:
        return

    specific_log_method = getattr(step_event_logger, f"log_{event_name}", None)
    if callable(specific_log_method):
        specific_log_method(**payload)
        return

    generic_log_method = getattr(step_event_logger, "log_event", None)
    if callable(generic_log_method):
        generic_log_method(event=event_name, **payload)
        return

    if callable(step_event_logger):
        step_event_logger(event=event_name, **payload)
        return

    raise TypeError(
        f"Step event logger {step_event_logger!r} does not provide `log_{event_name}(...)`, "
        "`log_event(...)`, and is not callable."
    )


def _merge_action_delta(robot_action: RobotAction, action_delta: dict[str, Any]) -> RobotAction:
    merged_action = dict(robot_action)
    for key, delta in action_delta.items():
        if (
            key in merged_action
            and isinstance(merged_action[key], numbers.Real)
            and isinstance(delta, numbers.Real)
        ):
            merged_action[key] = float(merged_action[key] + delta)
        else:
            merged_action[key] = delta
    return merged_action


_ACTION_COMMAND_FIELDS = {
    "joint_positions",
    "joint_deltas",
    "cartesian_target",
    "reference_frame",
    "gripper_closed",
    "label",
    "metadata",
}


def _is_finite_number(value: Any) -> bool:
    return isinstance(value, numbers.Real) and not isinstance(value, bool)


def _normalize_guard_decision(decision: Any) -> str | None:
    if decision is None:
        return None
    if hasattr(decision, "value"):
        decision = decision.value
    if isinstance(decision, str):
        normalized = decision.strip().lower()
        return normalized or None
    return None


def _get_action_reference_keys(
    action_template: Mapping[str, Any] | None,
    obs: Mapping[str, Any] | None,
) -> list[str]:
    if action_template is not None:
        action_keys = [key for key, value in action_template.items() if _is_finite_number(value)]
        if action_keys:
            return action_keys
    if obs is not None:
        obs_keys = [key for key, value in obs.items() if _is_finite_number(value)]
        if obs_keys:
            return obs_keys
    return []


def _is_action_command_payload(value: Any) -> bool:
    return (
        isinstance(value, Mapping)
        and bool(value)
        and set(value).issubset(_ACTION_COMMAND_FIELDS)
        and any(field in value for field in ("joint_positions", "joint_deltas", "cartesian_target", "gripper_closed"))
    )


def _convert_action_command_payload(
    command: Mapping[str, Any],
    *,
    action_template: Mapping[str, Any] | None,
    obs: Mapping[str, Any] | None,
) -> RobotAction:
    action_keys = _get_action_reference_keys(action_template, obs)
    obs_numeric = {
        key: float(value)
        for key, value in (obs.items() if obs is not None else [])
        if _is_finite_number(value)
    }

    joint_positions = command.get("joint_positions")
    if joint_positions is not None:
        positions = tuple(float(value) for value in joint_positions)
        if not action_keys:
            raise ValueError("Cannot map GuardResult joint_positions without numeric robot action or observation keys.")
        if len(positions) != len(action_keys):
            raise ValueError(
                f"GuardResult joint_positions length {len(positions)} does not match robot action dimension {len(action_keys)}."
            )
        return dict(zip(action_keys, positions, strict=True))

    joint_deltas = command.get("joint_deltas")
    if joint_deltas is not None:
        deltas = tuple(float(value) for value in joint_deltas)
        if not action_keys:
            raise ValueError("Cannot map GuardResult joint_deltas without numeric robot action or observation keys.")
        if len(deltas) != len(action_keys):
            raise ValueError(
                f"GuardResult joint_deltas length {len(deltas)} does not match robot action dimension {len(action_keys)}."
            )
        missing_keys = [key for key in action_keys if key not in obs_numeric]
        if missing_keys:
            raise ValueError(
                "Cannot map GuardResult joint_deltas without numeric observation values for "
                f"{missing_keys!r}."
            )
        return {
            key: obs_numeric[key] + delta for key, delta in zip(action_keys, deltas, strict=True)
        }

    if command.get("gripper_closed") is not None:
        gripper_keys = [key for key in action_keys if "gripper" in key.lower()]
        if len(gripper_keys) == 1:
            return {gripper_keys[0]: float(bool(command["gripper_closed"]))}
        raise ValueError("Cannot map GuardResult gripper_closed without a single gripper-like action key.")

    if command.get("cartesian_target") is not None:
        raise ValueError("Cannot map GuardResult cartesian_target into a generic robot action dict.")

    return {}


def _coerce_robot_action_candidate(
    candidate: Any,
    *,
    action_template: Mapping[str, Any] | None,
    obs: Mapping[str, Any] | None,
) -> RobotAction | None:
    if candidate is None:
        return None

    if _is_action_command_payload(candidate):
        return _convert_action_command_payload(candidate, action_template=action_template, obs=obs)

    if isinstance(candidate, Mapping):
        return dict(candidate)

    if is_dataclass(candidate) and not isinstance(candidate, type):
        candidate_payload = asdict(candidate)
        if _is_action_command_payload(candidate_payload):
            return _convert_action_command_payload(candidate_payload, action_template=action_template, obs=obs)
        if isinstance(candidate_payload, Mapping):
            return dict(candidate_payload)

    if hasattr(candidate, "__dict__"):
        candidate_payload = {key: value for key, value in vars(candidate).items() if not key.startswith("_")}
        if _is_action_command_payload(candidate_payload):
            return _convert_action_command_payload(candidate_payload, action_template=action_template, obs=obs)
        if isinstance(candidate_payload, Mapping):
            return dict(candidate_payload)

    return candidate


def _normalize_guard_result(
    guard_result: Any,
    *,
    requested_action: Mapping[str, Any] | None,
    obs: Mapping[str, Any] | None,
) -> dict[str, Any] | None:
    guard_payload = _coerce_hook_result(guard_result)
    if guard_payload is None:
        return None

    action_override = _coerce_robot_action_candidate(
        guard_payload.get("action"),
        action_template=requested_action,
        obs=obs,
    )
    fail_safe_action = _coerce_robot_action_candidate(
        guard_payload.get("fail_safe_action"),
        action_template=requested_action,
        obs=obs,
    )
    decision = _normalize_guard_decision(guard_payload.get("decision"))

    if decision is not None:
        accept = decision in {"accept", "clamp_and_accept"}
        halt = decision == "halt"
        if not accept and fail_safe_action is None and action_override is not None:
            fail_safe_action = action_override
        if accept:
            effective_action = requested_action if action_override is None else action_override
        else:
            effective_action = fail_safe_action
    else:
        accept = bool(guard_payload.get("accept", True))
        halt = bool(guard_payload.get("halt", False))
        if not accept and fail_safe_action is None and action_override is not None:
            fail_safe_action = action_override
        effective_action = requested_action
        if accept and action_override is not None:
            effective_action = action_override
        if not accept:
            effective_action = fail_safe_action

    normalized_payload = dict(guard_payload)
    normalized_payload["accept"] = accept
    normalized_payload["halt"] = halt
    if action_override is not None:
        normalized_payload["action"] = action_override
    if fail_safe_action is not None:
        normalized_payload["fail_safe_action"] = fail_safe_action
    if decision is not None:
        normalized_payload["decision"] = decision

    return {
        "payload": normalized_payload,
        "accept": accept,
        "halt": halt,
        "effective_action": effective_action,
        "skip_action_send": effective_action is None,
    }


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    policy_observation_features: dict[str, dict] | None = None,
    policy_action_features: dict[str, dict] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    perception_bridge: Any | None = None,
    safety_guard: Any | None = None,
    step_event_logger: Any | None = None,
    runtime_state: Any | None = None,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (so100_leader.SO100Leader | so101_leader.SO101Leader | koch_leader.KochLeader),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    step_index = _get_runtime_state_value(runtime_state, "step_index", 0)
    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()
        current_task = single_task
        bridge_decision = None
        guard_result = None
        sent_action = None
        persisted_action = None
        halt_requested = False
        skip_action_send = False

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        obs = robot.get_observation()

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        obs_processed = robot_observation_processor(obs)

        if perception_bridge is not None:
            bridge_decision = _invoke_hook(
                perception_bridge,
                "decide",
                obs=obs_processed,
                raw_obs=obs,
                runtime_state=runtime_state,
                task=current_task,
                step_index=step_index,
                timestamp=timestamp,
            )
            if bridge_decision and bridge_decision.get("task_override"):
                current_task = bridge_decision["task_override"]

        policy_observation_frame = None
        dataset_observation_frame = None
        if policy is not None:
            observation_features = (
                policy_observation_features
                if policy_observation_features is not None
                else (dataset.features if dataset is not None else None)
            )
            if observation_features is None:
                raise ValueError("Policy observation features are required when running a policy.")
            policy_observation_frame = build_dataset_frame(observation_features, obs_processed, prefix=OBS_STR)

        if dataset is not None:
            dataset_observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

        # Get action from either policy or teleop
        if policy is not None and preprocessor is not None and postprocessor is not None:
            action_values = predict_action(
                observation=policy_observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=current_task,
                robot_type=robot.robot_type,
            )
            action_features = (
                policy_action_features
                if policy_action_features is not None
                else (dataset.features if dataset is not None else None)
            )
            if action_features is None:
                raise ValueError("Policy action features are required when running a policy.")
            act_processed_policy = make_robot_action(action_values, action_features)

        elif policy is None and isinstance(teleop, Teleoperator):
            act = teleop.get_action()

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            act_processed_teleop = teleop_action_processor((act, obs))

        elif policy is None and isinstance(teleop, list):
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            act_processed_teleop = teleop_action_processor((act, obs))
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Applies a pipeline to the action, default is IdentityProcessor
        if policy is not None and act_processed_policy is not None:
            action_values = act_processed_policy
            robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        else:
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        if bridge_decision:
            action_override = bridge_decision.get("action")
            if action_override is not None:
                robot_action_to_send = _coerce_robot_action_candidate(
                    action_override,
                    action_template=robot_action_to_send,
                    obs=obs_processed,
                )
            action_delta = bridge_decision.get("action_delta")
            if action_delta:
                robot_action_to_send = _merge_action_delta(robot_action_to_send, action_delta)

        if safety_guard is not None:
            requested_action = robot_action_to_send
            raw_guard_result = _invoke_hook(
                safety_guard,
                "validate",
                action=robot_action_to_send,
                obs=obs_processed,
                raw_obs=obs,
                runtime_state=runtime_state,
                task=current_task,
                bridge_decision=bridge_decision,
                step_index=step_index,
                timestamp=timestamp,
            )
            guard_result = _normalize_guard_result(
                raw_guard_result,
                requested_action=robot_action_to_send,
                obs=obs_processed,
            )
            if guard_result is not None:
                robot_action_to_send = guard_result["effective_action"]
            if guard_result and not guard_result["accept"]:
                skip_action_send = guard_result["skip_action_send"]
                halt_requested = guard_result["halt"]
                if halt_requested:
                    events["stop_recording"] = True
                    _set_runtime_state_value(runtime_state, "halted", True)
                _log_step_event(
                    step_event_logger,
                    "guard_reject",
                    step_index=step_index,
                    task=current_task,
                    action=robot_action_to_send,
                    requested_action=requested_action,
                    obs=obs_processed,
                    raw_obs=obs,
                    bridge_decision=bridge_decision,
                    guard_result=guard_result["payload"],
                    halt=halt_requested,
                )

        # Send action to robot
        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset. action = postprocessor.process(action)
        # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.
        if not skip_action_send:
            sent_action = robot.send_action(robot_action_to_send)
            persisted_action = robot_action_to_send if sent_action is None else sent_action
            _log_step_event(
                step_event_logger,
                "step",
                step_index=step_index,
                task=current_task,
                action=robot_action_to_send,
                sent_action=sent_action,
                obs=obs_processed,
                raw_obs=obs,
                bridge_decision=bridge_decision,
                guard_result=None if guard_result is None else guard_result["payload"],
            )

        # Write to dataset
        if dataset is not None and persisted_action is not None:
            action_frame = build_dataset_frame(dataset.features, persisted_action, prefix=ACTION)
            frame = {**dataset_observation_frame, **action_frame, "task": current_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(observation=obs_processed, action=action_values if persisted_action is None else persisted_action)

        dt_s = time.perf_counter() - start_loop_t
        precise_sleep(1 / fps - dt_s)

        timestamp = time.perf_counter() - start_episode_t
        step_index += 1
        _set_runtime_state_value(runtime_state, "step_index", step_index)

        if halt_requested:
            break


@parser.wrap()
def record(
    cfg: RecordConfig,
    *,
    perception_bridge: Any | None = None,
    safety_guard: Any | None = None,
    step_event_logger: Any | None = None,
    runtime_state: Any | None = None,
) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording")

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )
    policy_observation_features = aggregate_pipeline_dataset_features(
        pipeline=robot_observation_processor,
        initial_features=create_initial_features(observation=robot.observation_features),
        use_videos=True,
    )

    if cfg.resume:
        dataset = LeRobotDataset(
            cfg.dataset.repo_id,
            root=cfg.dataset.root,
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

        if hasattr(robot, "cameras") and len(robot.cameras) > 0:
            dataset.start_image_writer(
                num_processes=cfg.dataset.num_image_writer_processes,
                num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            )
        sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
    else:
        # Create empty dataset or load existing saved episodes
        sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
        dataset = LeRobotDataset.create(
            cfg.dataset.repo_id,
            cfg.dataset.fps,
            root=cfg.dataset.root,
            robot_type=robot.name,
            features=dataset_features,
            use_videos=cfg.dataset.video,
            image_writer_processes=cfg.dataset.num_image_writer_processes,
            image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
            batch_encoding_size=cfg.dataset.video_encoding_batch_size,
        )

    # Load pretrained policy
    policy = None if cfg.policy is None else make_policy(
        cfg.policy,
        ds_meta=dataset.meta,
        rename_map=cfg.dataset.rename_map,
    )
    preprocessor = None
    postprocessor = None
    if cfg.policy is not None:
        preprocessor, postprocessor = make_pre_post_processors(
            policy_cfg=cfg.policy,
            pretrained_path=cfg.policy.pretrained_path,
            dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
            preprocessor_overrides={
                "device_processor": {"device": cfg.policy.device},
                "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
            },
        )

    robot.connect()
    if teleop is not None:
        teleop.connect()

    listener, events = init_keyboard_listener()

    with VideoEncodingManager(dataset):
        recorded_episodes = 0
        while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
            log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
            record_loop(
                robot=robot,
                events=events,
                fps=cfg.dataset.fps,
                teleop_action_processor=teleop_action_processor,
                robot_action_processor=robot_action_processor,
                robot_observation_processor=robot_observation_processor,
                teleop=teleop,
                policy=policy,
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                policy_observation_features=policy_observation_features,
                dataset=dataset,
                control_time_s=cfg.dataset.episode_time_s,
                single_task=cfg.dataset.single_task,
                display_data=cfg.display_data,
                perception_bridge=perception_bridge,
                safety_guard=safety_guard,
                step_event_logger=step_event_logger,
                runtime_state=runtime_state,
            )

            # Execute a few seconds without recording to give time to manually reset the environment
            # Skip reset for the last episode to be recorded
            if not events["stop_recording"] and (
                (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
            ):
                log_say("Reset the environment", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    control_time_s=cfg.dataset.reset_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    perception_bridge=perception_bridge,
                    safety_guard=safety_guard,
                    step_event_logger=step_event_logger,
                    runtime_state=runtime_state,
                )

            if events["rerecord_episode"]:
                log_say("Re-record episode", cfg.play_sounds)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                dataset.clear_episode_buffer()
                continue

            dataset.save_episode()
            recorded_episodes += 1

    log_say("Stop recording", cfg.play_sounds, blocking=True)

    robot.disconnect()
    if teleop is not None:
        teleop.disconnect()

    if not is_headless() and listener is not None:
        listener.stop()

    if cfg.dataset.push_to_hub:
        dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

    log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_devices()
    record()


if __name__ == "__main__":
    main()
